---
abstract: 'Client API and CLI for Moodle Web Services'
author:
  - 'Andrew Solomon <andrew@geekuni.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Moodle-Simple
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Data::Dumper: '0'
  HTTP::Request: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  List::Util: '0'
  Moo: '0'
  OptArgs: '0'
  Ouch: '0'
  Sys::SigAction: '0'
  URI: '0'
  namespace::clean: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/andrewsolomon/WebService-Moodle-Simple/issues
  homepage: https://github.com/andrewsolomon/WebService-Moodle-Simple
  repository: https://github.com/andrewsolomon/WebService-Moodle-Simple.git
version: '0.04'
x_contributors:
  - 'Andrew Solomon <andrew@illywhacker.net>'
